(package "vs-comment-return"
         "0.2.0"
         "Comment return like Visual Studio")

(website-url "https://github.com/emacs-vs/vs-comment-return")
(keywords "convenience")

(package-file "vs-comment-return.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "28.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
